// <auto-generated />
using System;
using LanguageReader.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LanguageReader.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260621125942_RemoveTranslatedRangeDictionaryForm")]
    partial class RemoveTranslatedRangeDictionaryForm
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LanguageReader.Infrastructure.Features.Ai.Entities.AiOperationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<decimal>("InputCostUsd")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("input_cost_usd");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("model");

                    b.Property<decimal>("OutputCostUsd")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("output_cost_usd");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider");

                    b.Property<decimal>("TotalCostUsd")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("total_cost_usd");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("integer")
                        .HasColumnName("total_tokens");

                    b.Property<Guid?>("TranslatedRangeId")
                        .HasColumnType("uuid")
                        .HasColumnName("translated_range_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("username");

                    b.Property<Guid?>("VocabularyEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("vocabulary_entry_id");

                    b.HasKey("Id");

                    b.HasIndex("TranslatedRangeId");

                    b.HasIndex("Username");

                    b.HasIndex("VocabularyEntryId");

                    b.ToTable("ai_operations", (string)null);
                });

            modelBuilder.Entity("LanguageReader.Infrastructure.Features.ReadingItemTranslations.Entities.TranslatedRangeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("EndOffset")
                        .HasColumnType("integer")
                        .HasColumnName("end_offset");

                    b.Property<string>("OriginalText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_text");

                    b.Property<int>("ParagraphIndex")
                        .HasColumnType("integer")
                        .HasColumnName("paragraph_index");

                    b.Property<Guid>("ReadingItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("reading_item_id");

                    b.Property<string>("ResolvedSelectionKind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("resolved_selection_kind");

                    b.Property<string>("SelectionKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Word")
                        .HasColumnName("selection_kind");

                    b.Property<bool>("ShowOriginal")
                        .HasColumnType("boolean")
                        .HasColumnName("show_original");

                    b.Property<int>("StartOffset")
                        .HasColumnType("integer")
                        .HasColumnName("start_offset");

                    b.Property<string>("TranslatedText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("translated_text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("username");

                    b.Property<Guid?>("VocabularyEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("vocabulary_entry_id");

                    b.HasKey("Id");

                    b.HasIndex("VocabularyEntryId");

                    b.HasIndex("ReadingItemId", "ParagraphIndex");

                    b.HasIndex("Username", "ReadingItemId");

                    b.ToTable("translated_ranges", (string)null);
                });

            modelBuilder.Entity("LanguageReader.Infrastructure.Features.Books.Entities.BookEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("OriginalLanguage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("Unknown")
                        .HasColumnName("original_language");

                    b.Property<string>("OwnerUsername")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("owner_username");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("storage_path");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("IsPublic");

                    b.HasIndex("OwnerUsername");

                    b.ToTable("books", (string)null);
                });

            modelBuilder.Entity("LanguageReader.Infrastructure.Features.News.Entities.RssArticleCandidateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("author");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("external_id");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("image_url");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<Guid?>("SavedReadingItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("saved_reading_item_id");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_key");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("SourceKey");

                    b.HasIndex("SourceKey", "ExternalId");

                    b.HasIndex("SourceKey", "Url")
                        .IsUnique();

                    b.ToTable("rss_article_candidates", (string)null);
                });

            modelBuilder.Entity("LanguageReader.Infrastructure.Features.Reading.Entities.ReadingProgressEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CharacterOffset")
                        .HasColumnType("integer")
                        .HasColumnName("character_offset");

                    b.Property<DateTimeOffset>("LastOpenedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_opened_at_utc");

                    b.Property<int>("ParagraphIndex")
                        .HasColumnType("integer")
                        .HasColumnName("paragraph_index");

                    b.Property<double>("ProgressPercent")
                        .HasColumnType("double precision")
                        .HasColumnName("progress_percent");

                    b.Property<Guid>("ReadingItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("reading_item_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("ReadingItemId");

                    b.HasIndex("Username", "ReadingItemId")
                        .IsUnique();

                    b.ToTable("reading_progress", (string)null);
                });

            modelBuilder.Entity("LanguageReader.Infrastructure.Features.ReadingItems.Entities.ArticleMetadataEntity", b =>
                {
                    b.Property<Guid>("ReadingItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("reading_item_id");

                    b.Property<string>("Author")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("author");

                    b.Property<string>("Excerpt")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("excerpt");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("external_id");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("image_url");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("original_url");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<string>("RssFeedUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("rss_feed_url");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_name");

                    b.HasKey("ReadingItemId");

                    b.HasIndex("ExternalId");

                    b.ToTable("article_metadata", (string)null);
                });

            modelBuilder.Entity("LanguageReader.Infrastructure.Features.ReadingItems.Entities.ReadingItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentFormat")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("content_format");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("OriginalLanguage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("original_language");

                    b.Property<string>("OwnerUsername")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("owner_username");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("storage_path");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("IsPublic");

                    b.HasIndex("OwnerUsername");

                    b.HasIndex("Type");

                    b.ToTable("reading_items", (string)null);
                });

            modelBuilder.Entity("LanguageReader.Infrastructure.Features.Settings.Entities.UserSettingsEntity", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("username");

                    b.Property<string>("AiServiceMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Fake")
                        .HasColumnName("ai_service_mode");

                    b.Property<string>("NativeLanguage")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("learning_language");

                    b.HasKey("Username");

                    b.ToTable("user_settings", (string)null);
                });

            modelBuilder.Entity("LanguageReader.Infrastructure.Features.Vocabulary.Entities.RelatedWordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<Guid>("VocabularyEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("vocabulary_entry_id");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("word");

                    b.HasKey("Id");

                    b.HasIndex("VocabularyEntryId");

                    b.ToTable("related_words", (string)null);
                });

            modelBuilder.Entity("LanguageReader.Infrastructure.Features.Vocabulary.Entities.VocabularyEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CharacterOffset")
                        .HasColumnType("integer")
                        .HasColumnName("character_offset");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsVisibleInVocabulary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_visible_in_vocabulary");

                    b.Property<int>("ParagraphIndex")
                        .HasColumnType("integer")
                        .HasColumnName("paragraph_index");

                    b.Property<Guid>("ReadingItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("reading_item_id");

                    b.Property<string>("SelectionKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("selection_kind");

                    b.Property<string>("SourceLanguage")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_language");

                    b.Property<string>("TargetLanguage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("target_language");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("translation");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("username");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("word");

                    b.HasKey("Id");

                    b.HasIndex("ReadingItemId");

                    b.HasIndex("Username");

                    b.ToTable("vocabulary_entries", (string)null);
                });

            modelBuilder.Entity("LanguageReader.Infrastructure.Features.Vocabulary.Entities.VocabularyExampleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("CharacterOffset")
                        .HasColumnType("integer")
                        .HasColumnName("character_offset");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsFromReadingItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_from_book");

                    b.Property<int?>("ParagraphIndex")
                        .HasColumnType("integer")
                        .HasColumnName("paragraph_index");

                    b.Property<Guid?>("ReadingItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("reading_item_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("Translation")
                        .HasColumnType("text")
                        .HasColumnName("translation");

                    b.Property<Guid>("VocabularyEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("vocabulary_entry_id");

                    b.HasKey("Id");

                    b.HasIndex("ReadingItemId");

                    b.HasIndex("VocabularyEntryId");

                    b.ToTable("vocabulary_examples", (string)null);
                });

            modelBuilder.Entity("LanguageReader.Infrastructure.Features.Vocabulary.Entities.VocabularyWordDetailsEntity", b =>
                {
                    b.Property<Guid>("VocabularyEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("vocabulary_entry_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DictionaryForm")
                        .HasColumnType("text")
                        .HasColumnName("dictionary_form");

                    b.Property<int?>("FrequencyScore")
                        .HasColumnType("integer")
                        .HasColumnName("frequency_score");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PartOfSpeech")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("part_of_speech");

                    b.Property<string>("SeenForm")
                        .HasColumnType("text")
                        .HasColumnName("seen_form");

                    b.HasKey("VocabularyEntryId");

                    b.ToTable("vocabulary_word_details", (string)null);
                });

            modelBuilder.Entity("LanguageReader.Infrastructure.Features.Ai.Entities.AiOperationEntity", b =>
                {
                    b.HasOne("LanguageReader.Infrastructure.Features.ReadingItemTranslations.Entities.TranslatedRangeEntity", "TranslatedRange")
                        .WithMany("AiOperations")
                        .HasForeignKey("TranslatedRangeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LanguageReader.Infrastructure.Features.Vocabulary.Entities.VocabularyEntryEntity", "VocabularyEntry")
                        .WithMany("AiOperations")
                        .HasForeignKey("VocabularyEntryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("TranslatedRange");

                    b.Navigation("VocabularyEntry");
                });

            modelBuilder.Entity("LanguageReader.Infrastructure.Features.ReadingItemTranslations.Entities.TranslatedRangeEntity", b =>
                {
                    b.HasOne("LanguageReader.Infrastructure.Features.ReadingItems.Entities.ReadingItemEntity", "Book")
                        .WithMany("TranslatedRanges")
                        .HasForeignKey("ReadingItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LanguageReader.Infrastructure.Features.Vocabulary.Entities.VocabularyEntryEntity", "VocabularyEntry")
                        .WithMany()
                        .HasForeignKey("VocabularyEntryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Book");

                    b.Navigation("VocabularyEntry");
                });

            modelBuilder.Entity("LanguageReader.Infrastructure.Features.Reading.Entities.ReadingProgressEntity", b =>
                {
                    b.HasOne("LanguageReader.Infrastructure.Features.ReadingItems.Entities.ReadingItemEntity", "Book")
                        .WithMany("ReadingProgresses")
                        .HasForeignKey("ReadingItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("LanguageReader.Infrastructure.Features.ReadingItems.Entities.ArticleMetadataEntity", b =>
                {
                    b.HasOne("LanguageReader.Infrastructure.Features.ReadingItems.Entities.ReadingItemEntity", "ReadingItem")
                        .WithOne("ArticleMetadata")
                        .HasForeignKey("LanguageReader.Infrastructure.Features.ReadingItems.Entities.ArticleMetadataEntity", "ReadingItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReadingItem");
                });

            modelBuilder.Entity("LanguageReader.Infrastructure.Features.Vocabulary.Entities.RelatedWordEntity", b =>
                {
                    b.HasOne("LanguageReader.Infrastructure.Features.Vocabulary.Entities.VocabularyEntryEntity", "VocabularyEntry")
                        .WithMany("RelatedWords")
                        .HasForeignKey("VocabularyEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VocabularyEntry");
                });

            modelBuilder.Entity("LanguageReader.Infrastructure.Features.Vocabulary.Entities.VocabularyEntryEntity", b =>
                {
                    b.HasOne("LanguageReader.Infrastructure.Features.ReadingItems.Entities.ReadingItemEntity", "Book")
                        .WithMany("VocabularyEntries")
                        .HasForeignKey("ReadingItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("LanguageReader.Infrastructure.Features.Vocabulary.Entities.VocabularyExampleEntity", b =>
                {
                    b.HasOne("LanguageReader.Infrastructure.Features.ReadingItems.Entities.ReadingItemEntity", "Book")
                        .WithMany()
                        .HasForeignKey("ReadingItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LanguageReader.Infrastructure.Features.Vocabulary.Entities.VocabularyEntryEntity", "VocabularyEntry")
                        .WithMany("Examples")
                        .HasForeignKey("VocabularyEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("VocabularyEntry");
                });

            modelBuilder.Entity("LanguageReader.Infrastructure.Features.Vocabulary.Entities.VocabularyWordDetailsEntity", b =>
                {
                    b.HasOne("LanguageReader.Infrastructure.Features.Vocabulary.Entities.VocabularyEntryEntity", "VocabularyEntry")
                        .WithOne("WordDetails")
                        .HasForeignKey("LanguageReader.Infrastructure.Features.Vocabulary.Entities.VocabularyWordDetailsEntity", "VocabularyEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VocabularyEntry");
                });

            modelBuilder.Entity("LanguageReader.Infrastructure.Features.ReadingItemTranslations.Entities.TranslatedRangeEntity", b =>
                {
                    b.Navigation("AiOperations");
                });

            modelBuilder.Entity("LanguageReader.Infrastructure.Features.ReadingItems.Entities.ReadingItemEntity", b =>
                {
                    b.Navigation("ArticleMetadata");

                    b.Navigation("ReadingProgresses");

                    b.Navigation("TranslatedRanges");

                    b.Navigation("VocabularyEntries");
                });

            modelBuilder.Entity("LanguageReader.Infrastructure.Features.Vocabulary.Entities.VocabularyEntryEntity", b =>
                {
                    b.Navigation("AiOperations");

                    b.Navigation("Examples");

                    b.Navigation("RelatedWords");

                    b.Navigation("WordDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
